// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: recordio/test_files/text_line.proto

package test_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int32                  `protobuf:"varint,1,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLine) Reset() {
	*x = TextLine{}
	mi := &file_recordio_test_files_text_line_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLine) ProtoMessage() {}

func (x *TextLine) ProtoReflect() protoreflect.Message {
	mi := &file_recordio_test_files_text_line_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLine.ProtoReflect.Descriptor instead.
func (*TextLine) Descriptor() ([]byte, []int) {
	return file_recordio_test_files_text_line_proto_rawDescGZIP(), []int{0}
}

func (x *TextLine) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *TextLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_recordio_test_files_text_line_proto protoreflect.FileDescriptor

var file_recordio_test_files_text_line_proto_rawDesc = string([]byte{
	0x0a, 0x23, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0x3e, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x68, 0x6f, 0x6d, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x62, 0x6c, 0x75, 0x74, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x69, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_recordio_test_files_text_line_proto_rawDescOnce sync.Once
	file_recordio_test_files_text_line_proto_rawDescData []byte
)

func file_recordio_test_files_text_line_proto_rawDescGZIP() []byte {
	file_recordio_test_files_text_line_proto_rawDescOnce.Do(func() {
		file_recordio_test_files_text_line_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recordio_test_files_text_line_proto_rawDesc), len(file_recordio_test_files_text_line_proto_rawDesc)))
	})
	return file_recordio_test_files_text_line_proto_rawDescData
}

var file_recordio_test_files_text_line_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_recordio_test_files_text_line_proto_goTypes = []any{
	(*TextLine)(nil), // 0: test_files.TextLine
}
var file_recordio_test_files_text_line_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recordio_test_files_text_line_proto_init() }
func file_recordio_test_files_text_line_proto_init() {
	if File_recordio_test_files_text_line_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recordio_test_files_text_line_proto_rawDesc), len(file_recordio_test_files_text_line_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recordio_test_files_text_line_proto_goTypes,
		DependencyIndexes: file_recordio_test_files_text_line_proto_depIdxs,
		MessageInfos:      file_recordio_test_files_text_line_proto_msgTypes,
	}.Build()
	File_recordio_test_files_text_line_proto = out.File
	file_recordio_test_files_text_line_proto_goTypes = nil
	file_recordio_test_files_text_line_proto_depIdxs = nil
}
