// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordio/test_files/text_line.proto

package test_files

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TextLine struct {
	LineNumber           int32    `protobuf:"varint,1,opt,name=lineNumber" json:"lineNumber,omitempty"`
	Line                 string   `protobuf:"bytes,2,opt,name=line" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextLine) Reset()         { *m = TextLine{} }
func (m *TextLine) String() string { return proto.CompactTextString(m) }
func (*TextLine) ProtoMessage()    {}
func (*TextLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_text_line_63575b1e04ed20e5, []int{0}
}
func (m *TextLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextLine.Unmarshal(m, b)
}
func (m *TextLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextLine.Marshal(b, m, deterministic)
}
func (dst *TextLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextLine.Merge(dst, src)
}
func (m *TextLine) XXX_Size() int {
	return xxx_messageInfo_TextLine.Size(m)
}
func (m *TextLine) XXX_DiscardUnknown() {
	xxx_messageInfo_TextLine.DiscardUnknown(m)
}

var xxx_messageInfo_TextLine proto.InternalMessageInfo

func (m *TextLine) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *TextLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*TextLine)(nil), "test_files.TextLine")
}

func init() {
	proto.RegisterFile("recordio/test_files/text_line.proto", fileDescriptor_text_line_63575b1e04ed20e5)
}

var fileDescriptor_text_line_63575b1e04ed20e5 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0xc9, 0xcc, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0x89, 0x4f, 0xcb, 0xcc, 0x49, 0x2d, 0xd6,
	0x2f, 0x49, 0xad, 0x28, 0x89, 0xcf, 0xc9, 0xcc, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x42, 0xc8, 0x29, 0xd9, 0x71, 0x71, 0x84, 0xa4, 0x56, 0x94, 0xf8, 0x64, 0xe6, 0xa5, 0x0a,
	0xc9, 0x71, 0x71, 0x81, 0x54, 0xf9, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0xb0, 0x06, 0x21, 0x89, 0x08, 0x09, 0x71, 0xb1, 0x80, 0x78, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x3f,
	0xc4, 0xa9, 0x79, 0x00, 0x00, 0x00,
}
