// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: sstables/proto/sstable.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueOffset uint64 `protobuf:"varint,2,opt,name=valueOffset,proto3" json:"valueOffset,omitempty"`
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstables_proto_sstable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sstables_proto_sstable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_sstables_proto_sstable_proto_rawDescGZIP(), []int{0}
}

func (x *IndexEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *IndexEntry) GetValueOffset() uint64 {
	if x != nil {
		return x.ValueOffset
	}
	return 0
}

type DataEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstables_proto_sstable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sstables_proto_sstable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_sstables_proto_sstable_proto_rawDescGZIP(), []int{1}
}

func (x *DataEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRecords uint64 `protobuf:"varint,1,opt,name=numRecords,proto3" json:"numRecords,omitempty"`
	MinKey     []byte `protobuf:"bytes,2,opt,name=minKey,proto3" json:"minKey,omitempty"`
	MaxKey     []byte `protobuf:"bytes,3,opt,name=maxKey,proto3" json:"maxKey,omitempty"`
	DataBytes  uint64 `protobuf:"varint,4,opt,name=dataBytes,proto3" json:"dataBytes,omitempty"`
	IndexBytes uint64 `protobuf:"varint,5,opt,name=indexBytes,proto3" json:"indexBytes,omitempty"`
	TotalBytes uint64 `protobuf:"varint,6,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sstables_proto_sstable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_sstables_proto_sstable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_sstables_proto_sstable_proto_rawDescGZIP(), []int{2}
}

func (x *MetaData) GetNumRecords() uint64 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *MetaData) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *MetaData) GetMaxKey() []byte {
	if x != nil {
		return x.MaxKey
	}
	return nil
}

func (x *MetaData) GetDataBytes() uint64 {
	if x != nil {
		return x.DataBytes
	}
	return 0
}

func (x *MetaData) GetIndexBytes() uint64 {
	if x != nil {
		return x.IndexBytes
	}
	return 0
}

func (x *MetaData) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_sstables_proto_sstable_proto protoreflect.FileDescriptor

var file_sstables_proto_sstable_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x21, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x75, 0x6d,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6d, 0x61, 0x78, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x6f, 0x6d, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x62, 0x6c,
	0x75, 0x74, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x73,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sstables_proto_sstable_proto_rawDescOnce sync.Once
	file_sstables_proto_sstable_proto_rawDescData = file_sstables_proto_sstable_proto_rawDesc
)

func file_sstables_proto_sstable_proto_rawDescGZIP() []byte {
	file_sstables_proto_sstable_proto_rawDescOnce.Do(func() {
		file_sstables_proto_sstable_proto_rawDescData = protoimpl.X.CompressGZIP(file_sstables_proto_sstable_proto_rawDescData)
	})
	return file_sstables_proto_sstable_proto_rawDescData
}

var file_sstables_proto_sstable_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sstables_proto_sstable_proto_goTypes = []interface{}{
	(*IndexEntry)(nil), // 0: proto.IndexEntry
	(*DataEntry)(nil),  // 1: proto.DataEntry
	(*MetaData)(nil),   // 2: proto.MetaData
}
var file_sstables_proto_sstable_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sstables_proto_sstable_proto_init() }
func file_sstables_proto_sstable_proto_init() {
	if File_sstables_proto_sstable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sstables_proto_sstable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstables_proto_sstable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sstables_proto_sstable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sstables_proto_sstable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sstables_proto_sstable_proto_goTypes,
		DependencyIndexes: file_sstables_proto_sstable_proto_depIdxs,
		MessageInfos:      file_sstables_proto_sstable_proto_msgTypes,
	}.Build()
	File_sstables_proto_sstable_proto = out.File
	file_sstables_proto_sstable_proto_rawDesc = nil
	file_sstables_proto_sstable_proto_goTypes = nil
	file_sstables_proto_sstable_proto_depIdxs = nil
}
