// Package testutil contains helpers shared by tests and benchmarks across the module.
package testutil

import (
	"math/rand"
	"slices"
	"strings"
)

// integer are the types that can hold the non-negative 31-bit values generated by Integers.
type integer interface {
	~int | ~int32 | ~int64 | ~uint | ~uint32 | ~uint64
}

// Bytes returns n random bytes. A nil rng uses the global source.
func Bytes(rng *rand.Rand, n int) []byte {
	b := make([]byte, n)
	if rng == nil {
		_, _ = rand.Read(b)
	} else {
		_, _ = rng.Read(b)
	}
	return b
}

// String returns a string of n random runes from [0, 255). Runes above 127 are encoded with two bytes, thus the
// string is longer than n bytes. A nil rng uses the global source.
func String(rng *rand.Rand, n int) string {
	return randomRunes(rng, n, 0, 255)
}

// Letters returns a string of n random lowercase ASCII letters. A nil rng uses the global source.
func Letters(rng *rand.Rand, n int) string {
	return randomRunes(rng, n, 'a', 26)
}

func randomRunes(rng *rand.Rand, n int, offset rune, count int32) string {
	intn := rand.Int31n
	if rng != nil {
		intn = rng.Int31n
	}

	builder := strings.Builder{}
	builder.Grow(n)
	for i := 0; i < n; i++ {
		builder.WriteRune(offset + intn(count))
	}
	return builder.String()
}

// Integers returns n random non-negative integers from [0, 2^31). A nil rng uses the global source.
func Integers[T integer](rng *rand.Rand, n int) []T {
	int31 := rand.Int31
	if rng != nil {
		int31 = rng.Int31
	}

	result := make([]T, n)
	for i := range result {
		result[i] = T(int31())
	}
	return result
}

// SortedIntegers is like Integers, but returns the integers sorted ascending.
func SortedIntegers[T integer](rng *rand.Rand, n int) []T {
	result := Integers[T](rng, n)
	slices.Sort(result)
	return result
}
