// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: simpledb/proto/compaction_metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompactionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// database root relative write path of the compaction result
	WritePath string `protobuf:"bytes,1,opt,name=writePath,proto3" json:"writePath,omitempty"`
	// database root relative desired replacement path for the compaction result
	ReplacementPath string `protobuf:"bytes,2,opt,name=replacementPath,proto3" json:"replacementPath,omitempty"`
	// database root relative set of paths that contributed to that compaction result
	SstablePaths  []string `protobuf:"bytes,3,rep,name=sstablePaths,proto3" json:"sstablePaths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactionMetadata) Reset() {
	*x = CompactionMetadata{}
	mi := &file_simpledb_proto_compaction_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionMetadata) ProtoMessage() {}

func (x *CompactionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_simpledb_proto_compaction_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionMetadata.ProtoReflect.Descriptor instead.
func (*CompactionMetadata) Descriptor() ([]byte, []int) {
	return file_simpledb_proto_compaction_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *CompactionMetadata) GetWritePath() string {
	if x != nil {
		return x.WritePath
	}
	return ""
}

func (x *CompactionMetadata) GetReplacementPath() string {
	if x != nil {
		return x.ReplacementPath
	}
	return ""
}

func (x *CompactionMetadata) GetSstablePaths() []string {
	if x != nil {
		return x.SstablePaths
	}
	return nil
}

var File_simpledb_proto_compaction_metadata_proto protoreflect.FileDescriptor

var file_simpledb_proto_compaction_metadata_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x80, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x22, 0x0a, 0x0c, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x6f, 0x6d, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x62, 0x6c, 0x75,
	0x74, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_simpledb_proto_compaction_metadata_proto_rawDescOnce sync.Once
	file_simpledb_proto_compaction_metadata_proto_rawDescData []byte
)

func file_simpledb_proto_compaction_metadata_proto_rawDescGZIP() []byte {
	file_simpledb_proto_compaction_metadata_proto_rawDescOnce.Do(func() {
		file_simpledb_proto_compaction_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simpledb_proto_compaction_metadata_proto_rawDesc), len(file_simpledb_proto_compaction_metadata_proto_rawDesc)))
	})
	return file_simpledb_proto_compaction_metadata_proto_rawDescData
}

var file_simpledb_proto_compaction_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_simpledb_proto_compaction_metadata_proto_goTypes = []any{
	(*CompactionMetadata)(nil), // 0: proto.CompactionMetadata
}
var file_simpledb_proto_compaction_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simpledb_proto_compaction_metadata_proto_init() }
func file_simpledb_proto_compaction_metadata_proto_init() {
	if File_simpledb_proto_compaction_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simpledb_proto_compaction_metadata_proto_rawDesc), len(file_simpledb_proto_compaction_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simpledb_proto_compaction_metadata_proto_goTypes,
		DependencyIndexes: file_simpledb_proto_compaction_metadata_proto_depIdxs,
		MessageInfos:      file_simpledb_proto_compaction_metadata_proto_msgTypes,
	}.Build()
	File_simpledb_proto_compaction_metadata_proto = out.File
	file_simpledb_proto_compaction_metadata_proto_goTypes = nil
	file_simpledb_proto_compaction_metadata_proto_depIdxs = nil
}
