// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: simpledb/proto/wal_mutation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertMutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpsertMutation) Reset() {
	*x = UpsertMutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMutation) ProtoMessage() {}

func (x *UpsertMutation) ProtoReflect() protoreflect.Message {
	mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMutation.ProtoReflect.Descriptor instead.
func (*UpsertMutation) Descriptor() ([]byte, []int) {
	return file_simpledb_proto_wal_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertMutation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpsertMutation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteTombstoneMutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteTombstoneMutation) Reset() {
	*x = DeleteTombstoneMutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTombstoneMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTombstoneMutation) ProtoMessage() {}

func (x *DeleteTombstoneMutation) ProtoReflect() protoreflect.Message {
	mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTombstoneMutation.ProtoReflect.Descriptor instead.
func (*DeleteTombstoneMutation) Descriptor() ([]byte, []int) {
	return file_simpledb_proto_wal_mutation_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteTombstoneMutation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type WalMutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mutation:
	//	*WalMutation_Addition
	//	*WalMutation_DeleteTombStone
	Mutation isWalMutation_Mutation `protobuf_oneof:"mutation"`
}

func (x *WalMutation) Reset() {
	*x = WalMutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalMutation) ProtoMessage() {}

func (x *WalMutation) ProtoReflect() protoreflect.Message {
	mi := &file_simpledb_proto_wal_mutation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalMutation.ProtoReflect.Descriptor instead.
func (*WalMutation) Descriptor() ([]byte, []int) {
	return file_simpledb_proto_wal_mutation_proto_rawDescGZIP(), []int{2}
}

func (m *WalMutation) GetMutation() isWalMutation_Mutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (x *WalMutation) GetAddition() *UpsertMutation {
	if x, ok := x.GetMutation().(*WalMutation_Addition); ok {
		return x.Addition
	}
	return nil
}

func (x *WalMutation) GetDeleteTombStone() *DeleteTombstoneMutation {
	if x, ok := x.GetMutation().(*WalMutation_DeleteTombStone); ok {
		return x.DeleteTombStone
	}
	return nil
}

type isWalMutation_Mutation interface {
	isWalMutation_Mutation()
}

type WalMutation_Addition struct {
	Addition *UpsertMutation `protobuf:"bytes,1,opt,name=addition,proto3,oneof"`
}

type WalMutation_DeleteTombStone struct {
	DeleteTombStone *DeleteTombstoneMutation `protobuf:"bytes,2,opt,name=deleteTombStone,proto3,oneof"`
}

func (*WalMutation_Addition) isWalMutation_Mutation() {}

func (*WalMutation_DeleteTombStone) isWalMutation_Mutation() {}

var File_simpledb_proto_wal_mutation_proto protoreflect.FileDescriptor

var file_simpledb_proto_wal_mutation_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x61, 0x6c, 0x5f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f,
	0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x9a, 0x01, 0x0a, 0x0b, 0x57, 0x61, 0x6c, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x33, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f,
	0x6d, 0x62, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x6d, 0x62, 0x53, 0x74, 0x6f,
	0x6e, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x6f,
	0x6d, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x62, 0x6c, 0x75, 0x74, 0x2f, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_simpledb_proto_wal_mutation_proto_rawDescOnce sync.Once
	file_simpledb_proto_wal_mutation_proto_rawDescData = file_simpledb_proto_wal_mutation_proto_rawDesc
)

func file_simpledb_proto_wal_mutation_proto_rawDescGZIP() []byte {
	file_simpledb_proto_wal_mutation_proto_rawDescOnce.Do(func() {
		file_simpledb_proto_wal_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(file_simpledb_proto_wal_mutation_proto_rawDescData)
	})
	return file_simpledb_proto_wal_mutation_proto_rawDescData
}

var file_simpledb_proto_wal_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simpledb_proto_wal_mutation_proto_goTypes = []interface{}{
	(*UpsertMutation)(nil),          // 0: proto.UpsertMutation
	(*DeleteTombstoneMutation)(nil), // 1: proto.DeleteTombstoneMutation
	(*WalMutation)(nil),             // 2: proto.WalMutation
}
var file_simpledb_proto_wal_mutation_proto_depIdxs = []int32{
	0, // 0: proto.WalMutation.addition:type_name -> proto.UpsertMutation
	1, // 1: proto.WalMutation.deleteTombStone:type_name -> proto.DeleteTombstoneMutation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_simpledb_proto_wal_mutation_proto_init() }
func file_simpledb_proto_wal_mutation_proto_init() {
	if File_simpledb_proto_wal_mutation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simpledb_proto_wal_mutation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertMutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpledb_proto_wal_mutation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTombstoneMutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpledb_proto_wal_mutation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalMutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_simpledb_proto_wal_mutation_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WalMutation_Addition)(nil),
		(*WalMutation_DeleteTombStone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simpledb_proto_wal_mutation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simpledb_proto_wal_mutation_proto_goTypes,
		DependencyIndexes: file_simpledb_proto_wal_mutation_proto_depIdxs,
		MessageInfos:      file_simpledb_proto_wal_mutation_proto_msgTypes,
	}.Build()
	File_simpledb_proto_wal_mutation_proto = out.File
	file_simpledb_proto_wal_mutation_proto_rawDesc = nil
	file_simpledb_proto_wal_mutation_proto_goTypes = nil
	file_simpledb_proto_wal_mutation_proto_depIdxs = nil
}
