// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: _examples/proto/hello_world.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloWorld struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloWorld) Reset() {
	*x = HelloWorld{}
	if protoimpl.UnsafeEnabled {
		mi := &file___examples_proto_hello_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorld) ProtoMessage() {}

func (x *HelloWorld) ProtoReflect() protoreflect.Message {
	mi := &file___examples_proto_hello_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorld.ProtoReflect.Descriptor instead.
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return file___examples_proto_hello_world_proto_rawDescGZIP(), []int{0}
}

func (x *HelloWorld) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File___examples_proto_hello_world_proto protoreflect.FileDescriptor

var file___examples_proto_hello_world_proto_rawDesc = []byte{
	0x0a, 0x21, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x68, 0x6f, 0x6d, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x62, 0x6c, 0x75, 0x74, 0x2f,
	0x67, 0x6f, 0x2d, 0x73, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file___examples_proto_hello_world_proto_rawDescOnce sync.Once
	file___examples_proto_hello_world_proto_rawDescData = file___examples_proto_hello_world_proto_rawDesc
)

func file___examples_proto_hello_world_proto_rawDescGZIP() []byte {
	file___examples_proto_hello_world_proto_rawDescOnce.Do(func() {
		file___examples_proto_hello_world_proto_rawDescData = protoimpl.X.CompressGZIP(file___examples_proto_hello_world_proto_rawDescData)
	})
	return file___examples_proto_hello_world_proto_rawDescData
}

var file___examples_proto_hello_world_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file___examples_proto_hello_world_proto_goTypes = []any{
	(*HelloWorld)(nil), // 0: proto.HelloWorld
}
var file___examples_proto_hello_world_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file___examples_proto_hello_world_proto_init() }
func file___examples_proto_hello_world_proto_init() {
	if File___examples_proto_hello_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file___examples_proto_hello_world_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HelloWorld); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file___examples_proto_hello_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___examples_proto_hello_world_proto_goTypes,
		DependencyIndexes: file___examples_proto_hello_world_proto_depIdxs,
		MessageInfos:      file___examples_proto_hello_world_proto_msgTypes,
	}.Build()
	File___examples_proto_hello_world_proto = out.File
	file___examples_proto_hello_world_proto_rawDesc = nil
	file___examples_proto_hello_world_proto_goTypes = nil
	file___examples_proto_hello_world_proto_depIdxs = nil
}
