name: simpledb-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Linearization Test
        run: make linear-simpledb
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: simpledb/porcupine/*.html
      - name: Crash Test
        run: make crash-simpledb
